/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProgramsRouteRouteImport } from './routes/_app/programs/route'
import { Route as AppFlowsheetsRouteRouteImport } from './routes/_app/flowsheets/route'
import { Route as AppCoursesRouteRouteImport } from './routes/_app/courses/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppSiteGenerationsIndexRouteImport } from './routes/_app/site-generations/index'
import { Route as AppProgramsIndexRouteImport } from './routes/_app/programs/index'
import { Route as AppFlowsheetsIndexRouteImport } from './routes/_app/flowsheets/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppFlowsheetsFlowsheetIdRouteImport } from './routes/_app/flowsheets/$flowsheetId'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramsRouteRoute = AppProgramsRouteRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlowsheetsRouteRoute = AppFlowsheetsRouteRouteImport.update({
  id: '/flowsheets',
  path: '/flowsheets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSiteGenerationsIndexRoute = AppSiteGenerationsIndexRouteImport.update({
  id: '/site-generations/',
  path: '/site-generations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgramsIndexRoute = AppProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProgramsRouteRoute,
} as any)
const AppFlowsheetsIndexRoute = AppFlowsheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFlowsheetsRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppFlowsheetsFlowsheetIdRoute =
  AppFlowsheetsFlowsheetIdRouteImport.update({
    id: '/$flowsheetId',
    path: '/$flowsheetId',
    getParentRoute: () => AppFlowsheetsRouteRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/courses': typeof AppCoursesRouteRouteWithChildren
  '/flowsheets': typeof AppFlowsheetsRouteRouteWithChildren
  '/programs': typeof AppProgramsRouteRouteWithChildren
  '/flowsheets/$flowsheetId': typeof AppFlowsheetsFlowsheetIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/flowsheets/': typeof AppFlowsheetsIndexRoute
  '/programs/': typeof AppProgramsIndexRoute
  '/site-generations/': typeof AppSiteGenerationsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/flowsheets/$flowsheetId': typeof AppFlowsheetsFlowsheetIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/flowsheets': typeof AppFlowsheetsIndexRoute
  '/programs': typeof AppProgramsIndexRoute
  '/site-generations': typeof AppSiteGenerationsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteRouteWithChildren
  '/_app/flowsheets': typeof AppFlowsheetsRouteRouteWithChildren
  '/_app/programs': typeof AppProgramsRouteRouteWithChildren
  '/_app/flowsheets/$flowsheetId': typeof AppFlowsheetsFlowsheetIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/flowsheets/': typeof AppFlowsheetsIndexRoute
  '/_app/programs/': typeof AppProgramsIndexRoute
  '/_app/site-generations/': typeof AppSiteGenerationsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/courses'
    | '/flowsheets'
    | '/programs'
    | '/flowsheets/$flowsheetId'
    | '/courses/'
    | '/flowsheets/'
    | '/programs/'
    | '/site-generations/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/flowsheets/$flowsheetId'
    | '/courses'
    | '/flowsheets'
    | '/programs'
    | '/site-generations'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/courses'
    | '/_app/flowsheets'
    | '/_app/programs'
    | '/_app/flowsheets/$flowsheetId'
    | '/_app/courses/'
    | '/_app/flowsheets/'
    | '/_app/programs/'
    | '/_app/site-generations/'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/flowsheets': {
      id: '/_app/flowsheets'
      path: '/flowsheets'
      fullPath: '/flowsheets'
      preLoaderRoute: typeof AppFlowsheetsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/site-generations/': {
      id: '/_app/site-generations/'
      path: '/site-generations'
      fullPath: '/site-generations/'
      preLoaderRoute: typeof AppSiteGenerationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/programs/': {
      id: '/_app/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof AppProgramsIndexRouteImport
      parentRoute: typeof AppProgramsRouteRoute
    }
    '/_app/flowsheets/': {
      id: '/_app/flowsheets/'
      path: '/'
      fullPath: '/flowsheets/'
      preLoaderRoute: typeof AppFlowsheetsIndexRouteImport
      parentRoute: typeof AppFlowsheetsRouteRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/_app/flowsheets/$flowsheetId': {
      id: '/_app/flowsheets/$flowsheetId'
      path: '/$flowsheetId'
      fullPath: '/flowsheets/$flowsheetId'
      preLoaderRoute: typeof AppFlowsheetsFlowsheetIdRouteImport
      parentRoute: typeof AppFlowsheetsRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppCoursesRouteRouteChildren {
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppFlowsheetsRouteRouteChildren {
  AppFlowsheetsFlowsheetIdRoute: typeof AppFlowsheetsFlowsheetIdRoute
  AppFlowsheetsIndexRoute: typeof AppFlowsheetsIndexRoute
}

const AppFlowsheetsRouteRouteChildren: AppFlowsheetsRouteRouteChildren = {
  AppFlowsheetsFlowsheetIdRoute: AppFlowsheetsFlowsheetIdRoute,
  AppFlowsheetsIndexRoute: AppFlowsheetsIndexRoute,
}

const AppFlowsheetsRouteRouteWithChildren =
  AppFlowsheetsRouteRoute._addFileChildren(AppFlowsheetsRouteRouteChildren)

interface AppProgramsRouteRouteChildren {
  AppProgramsIndexRoute: typeof AppProgramsIndexRoute
}

const AppProgramsRouteRouteChildren: AppProgramsRouteRouteChildren = {
  AppProgramsIndexRoute: AppProgramsIndexRoute,
}

const AppProgramsRouteRouteWithChildren =
  AppProgramsRouteRoute._addFileChildren(AppProgramsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppFlowsheetsRouteRoute: typeof AppFlowsheetsRouteRouteWithChildren
  AppProgramsRouteRoute: typeof AppProgramsRouteRouteWithChildren
  AppSiteGenerationsIndexRoute: typeof AppSiteGenerationsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppFlowsheetsRouteRoute: AppFlowsheetsRouteRouteWithChildren,
  AppProgramsRouteRoute: AppProgramsRouteRouteWithChildren,
  AppSiteGenerationsIndexRoute: AppSiteGenerationsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
