services:
  dev:
    image: node:22-alpine
    container_name: flowstruct-dev
    working_dir: /flowstruct-app
    volumes:
      - ../../flowstruct-app:/flowstruct-app
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
    command: sh
    environment:
      NODE_ENV: development
