[tools]
java = "21"
node = { version = "24", postinstall = "corepack enable" }
maven = "3"

[env]
SPRING_PROFILES_ACTIVE = "dev"
NODE_ENV = "dev"

[tasks]
"deps:client" = { run = "cd client && pnpm install" }
"deps:api" = { run = "cd api && mvn dependency:resolve" }
deps = { depends = "[deps:*]" }
db = { run = "cd api && docker compose up" }
"db:down" = { run = "cd api && docker compose down -v" }
api = { run = "cd api && mvn clean spring-boot:run" }
client = { run = "cd client && pnpm start:cms" }
