spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/flowstruct
    username: flowstruct
    password: flowstruct
  flyway:
    user: flowstruct
    password: flowstruct
    locations: "classpath:db/migration,classpath:dev/db/migration"
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      springframework: DEBUG

secure: false

api:
  key: super-secret-api-key