spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/flowstruct}
    username: flowstruct
    password: flowstruct
  flyway:
    user: flowstruct
    password: flowstruct
    locations: "classpath:db/migration,classpath:dev/db/migration"
  config:
    activate:
      on-profile: dev

secure: false

site-generator:
  api-key: super-secret-api-key
  dir: ../client/apps/content
  script: "pnpm run build"
  iconPath: ../client/apps/content/src/assets/icon.png
