spring:
  application:
    name: flowstruct-api
  datasource:
    url: jdbc:postgresql://database/${DB_NAME:flowstruct}
    username: ${DB_USER:flowstruct}
    password: ${DB_PASSWORD:flowstruct}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${DB_USER:flowstruct}
    password: ${DB_PASSWORD:flowstruct}
  servlet:
    multipart:
      max-file-size: -1
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: health
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 31536000s
          public: true
          must-revalidate: true
          no-transform: true
  server:
    forward-headers-strategy: native

jwt:
  cookie:
    expiry: 1800

secure: true

site-generator:
  dir: ${SITE_GENERATOR_DIR}
  icon-dir: ${SITE_GENERATOR_ICON_DIR:}
  script: ${SITE_GENERATOR_SCRIPT}
  api-key: ${SITE_GENERATOR_API_KEY}
